services:
  4WEBD_DB:
    image: postgres
    build:
      context: .
      dockerfile: ./Postgres/Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=USER_DB
    networks:
      - 4WEBD_network
    ports:
      - "5432:5432"
    volumes:
      - 4WEBD_DB_data:/var/lib/postgresql/data
      - ./Postgres/init-scripts/entrypoint.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
  4WEBD_ApiGateway:
    image: 4webd_apigateway
    build:
      context: .
      dockerfile: 4WEBD.Gateways\Dockerfile
    networks:
      - 4WEBD_network
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  4WEBD_USER:
    image: 4webd_user
    build:
      context: .
      dockerfile: 4WEBD.User\Dockerfile
    networks:
      - 4WEBD_network
      - 4WEBD_notification_network
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__4WEBD_USER_DB=Host=4WEBD_DB;Username=admin;Password=secret;Database=USER_DB
  
  SUPMAP_RabbitMQ:
    image: rabbitmq:4.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret
    networks:
      - 4WEBD_notification_network
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  4WEBD_Notification:
    image: 4webd_notification
    build:
      context: .
      dockerfile: 4WEBD.NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RABBITMQ_CONNECTIONSTRING=${RABBITMQ_CONNECTIONSTRING}
    networks:
      - 4WEBD_network
      - 4WEBD_notification_network
    depends_on:
      - SUPMAP_RabbitMQ 
    

networks:
  4WEBD_network:
    driver: bridge
  4WEBD_notification_network:
    driver: bridge

volumes:
  4WEBD_DB_data:
    driver: local
